### ISSUE TITLE
Cannot create property 'scope' on string 'languages.0.language_code'

### ISSUE THREAD

**Issue by andrii-trush** [RobertGlynWilliams/vee-validate-laravel#3]
```
Uncaught (in promise) TypeError: Cannot create property 'scope' on string 'languages.0.language_code'
    at ErrorBag._normalizeError (vee-validate.esm.js?b14b:1025)
    at ErrorBag.add (vee-validate.esm.js?b14b:1006)
    at VueComponent.Vue.$setLaravelValidationErrorsFromResponse (vee-validate-laravel.js?ded8:35)
```

**Comment by liliumdev** [comment]
@andrii-trush You have to replace [this line ](https://github.com/RobertGlynWilliams/vee-validate-laravel/blob/master/src/vee-validate-laravel.js#L24) with `this.$validator.errors.add({ field: field, msg: errorString });` in order to use the newest version of Vee Validate with this package.

**Comment by rubanraj54** [comment]
is this fix included in version '1.0.1' ? Today i have installed this package, and getting the same error...

**Comment by o-leolleo** [comment]
@rubanraj54 there is actually a [pull request](https://github.com/RobertGlynWilliams/vee-validate-laravel/pull/4) on this issue. I've got to this error on a already running project. My workaround was to apply @liliumdev 's solution on a fork, and then made the project use my version, with the fix. Is there any news on this issue?

**Comment by o-leolleo** [comment]
oh, as of #5 things seems to be well known, but not fixed

**Comment by RobertGlynWilliams** [comment]
Sorry, I have been very busy.
Project has been updated.

**Comment by rubanraj54** [comment]
@leolleocomp  i used the same workaround as mentioned by @liliumdev. But looks like this has been included in to current version. I need to check once again.
