### ISSUE TITLE
Error with Laravel 5.7 and last version of v-validate

### ISSUE THREAD

**Issue by lucabecchetti** [RobertGlynWilliams/vee-validate-laravel#6]
I have to fix this line to work:

vee-validate-laravel.js line 37:

change this:

this$1.$validator.errors.add( field, errorString);

with this:

this$1.$validator.errors.add({field: field, msg: errorString});

**Comment by RobertGlynWilliams** [comment]
Sorry, I have been very busy.
Project has been updated.
